name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: windows-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: ashkantaravati/NuxtToGithubPages@v1.0
      with:
        username: 'Kropka8o'
        reponame: 'Portfolio'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
